#!/system/bin/sh
RAMSIZE=`grep MemTotal /proc/meminfo | awk '{ print \$2 }'`
ZRAMSIZE=$(($RAMSIZE*100))
if [ $1 ]; then
  mount -o rw,remount /system /system
  if [ $1 == "enable" ]; then
	echo "#!/system/bin/sh" > /etc/init.d/05zram
	echo "modprobe zram" >> /etc/init.d/05zram
	echo "echo 1 > /sys/block/zram0/reset" >> /etc/init.d/05zram
	echo "echo $ZRAMSIZE > /sys/block/zram0/disksize" >> /etc/init.d/05zram
	echo "mkswap /dev/block/zram0" >> /etc/init.d/05zram
	echo "swapon /dev/block/zram0" >> /etc/init.d/05zram
	chmod 555 /etc/init.d/05zram
	modprobe zram
	/etc/init.d/05zram
	echo "zram enabled and activated"
  else 
	swapoff /dev/block/zram0
	echo 1 > /sys/block/zram0/reset
	rmmod zram
	rm /etc/init.d/05zram
	echo "zram deactivated and disabled"
  fi
  mount -o ro,remount /system /system
else
  free | tail -1 
fi
